# Site
#repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Ifta Noor Mahmood
title: Software Engineer
email: iftalab@gmail.com
website: https://iftalab.github.io/

# Social links
#twitter_username: facespics
github_username:  iftalab
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: iftanoor
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ifta and I'm a software engineer.

  Need a mobile app from requirement analysis to shippable product? 

  With fair knowledge in requirement analysis, experience in REST api with node js and professional experience of 2.5 years of android app development, You can rely on me.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Cooking
   - Gaming

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
